<section class="content clearfix">
	<div class="privacy">
		<h4>Informativa sulla privacy.</h4>
		<p>
			In questa pagina si descrivono le modalità di gestione del sito in riferimento al trattamento dei dati personali degli utenti che lo consultano.<br>
			Si tratta di un'informativa che è resa anche ai sensi dell'art. 7 del Decreto Legislativo n.196 del 30/6/2003 "Codice in materia di protezione dei dati personali".<br>
			L'informativa è resa solo per il sito www.thubbl.com e non anche per altri siti web eventualmente consultati dall'utente tramite link 
			(ad esempio i siti dei partner commerciali o il sito di vendita dei biglietti via internet).<br>
			A seguito della consultazione di questo sito possono essere trattati dati relativi a persone identificate o identificabili.<br>
			Il titolare del loro trattamento è Filippo Matteo Riggio (CF. RGGFPP89C16G273W) che risiede in Via Brancon, 116 - 37054 Nogara (VR), al quale puoi rivolgerti 
			per esercitare i diritti sui tuoi dati: verificarne l'esistenza, il contenuto, l'origine e l'esattezza, richiederne l'integrazione, l'aggiornamento, 
			la correzione, la cancellazione, la trasformazione in forma anonima, il blocco dei dati trattati in violazione di legge, nonché opporsi in ogni caso al loro 
			trattamento (alla fine di questa pagina puoi trovare il testo integrale sui tuoi diritti).<br>
			I trattamenti sono curati solo dal titolare del trattamento, oppure da eventuali incaricati di occasionali operazioni di manutenzione.<br>
			Nessun dato derivante dal servizio web viene comunicato o diffuso, con le seguenti eccezioni:<br>
			i dati personali forniti dagli utenti che inoltrano richieste di invio di materiale (informazioni), utilizzati al solo fine di eseguire il servizio o la prestazione richiesta, 
			sono comunicati a terzi nel solo caso in cui ciò sia a tal fine necessario (servizi di spedizione);<br>
			i dati di coloro che accettano di ricevere comunicazioni di carattere commerciale potranno essere trattati da terzi incaricati da Filippo Matteo Riggio 
			ai fini dell'espletamento di ricerche di mercato o operazioni di direct marketing, sempre comunque inerenti alle attività di www.thubbl.com.
			I dati personali sono trattati con strumenti automatizzati per il tempo strettamente necessario a conseguire gli scopi per cui sono stati raccolti. 
			Specifiche misure di sicurezza sono osservate per prevenire la perdita dei dati, usi illeciti o non corretti ed accessi non autorizzati.<br><br>
			<strong>TIPI DI DATI TRATTATI</strong><br>
			Dati forniti volontariamente dall'utente<br>
			L'invio facoltativo, esplicito e volontario di posta elettronica agli indirizzi indicati su questo sito comporta la successiva acquisizione 
			dell'indirizzo del mittente, necessario per rispondere alle richieste, nonché degli eventuali altri dati personali inseriti nella missiva. 
			A parte quanto specificato più sotto per i dati di navigazione, l'utente è libero di fornire i dati personali richiesti nei moduli. 
			Il loro mancato conferimento può comportare l'impossibilità di ottenere quanto richiesto.<br>
			Le finalità dei singoli trattamenti sono indicate di volta in volta nel singolo modulo di richiesta.<br>
			Dati di navigazione<br>
			I sistemi informatici e le procedure software preposte al funzionamento di questo sito web acquisiscono, nel corso del loro normale esercizio, 
			alcuni dati personali la cui trasmissione è implicita nell'uso dei protocolli di comunicazione di Internet. 
			Si tratta di informazioni che non sono raccolte per essere associate a interessati identificati, ma che per loro stessa natura potrebbero, attraverso 
			elaborazioni ed associazioni con dati detenuti da terzi, permettere di identificare gli utenti.<br>
			In questa categoria di dati rientrano gli indirizzi IP o i nomi a dominio dei computer utilizzati dagli utenti che si connettono al sito, 
			gli indirizzi in notazione URI (Uniform Resource Identifier) delle risorse richieste, l'orario della richiesta, il metodo utilizzato nel sottoporre la 
			richiesta al server ed altri dettagli relativi al protocollo di comunicazione, al sistema operativo e all'ambiente informatico dell'utente.<br>
			Questi dati vengono utilizzati al solo fine di ricavare informazioni statistiche anonime sull'uso del sito e per controllarne il corretto funzionamento. 
			I dati potrebbero essere utilizzati per l'accertamento di responsabilità in caso di ipotetici reati informatici ai danni del sito.<br>
			Cookies<br>
			L'uso di c.d. cookie di sessione (che non vengono memorizzati in modo persistente sul computer dell'utente e svaniscono con la chiusura del browser) è 
			strettamente limitato alla trasmissione di identificativi di sessione (costituiti da numeri casuali generati dal server) necessari per consentire 
			l'esplorazione sicura ed efficiente del sito. I c.d. cookie di sessione utilizzati in questo sito evitano il ricorso ad altre tecniche informatiche 
			potenzialmente pregiudizievoli per la riservatezza della navigazione degli utenti e non consentono l'acquisizione di dati personali identificativi 
			dell'utente.<br><br>
			<strong>DIRITTI DEGLI INTERESSATI</strong><br>
			I soggetti cui si riferiscono i dati personali hanno i seguenti diritti:<br><br>
			Art. 7 del D.l. 196 del 30/6/2003<br>
			(Diritto di accesso ai dati personali ed altri diritti)<br>
			L'interessato ha diritto di ottenere la conferma dell'esistenza o meno di dati personali che lo riguardano, anche se non ancora registrati, 
			e la loro comunicazione in forma intelligibile.<br>
			L'interessato ha diritto di ottenere l'indicazione:<br>
			dell'origine dei dati personali;<br>
			delle finalità e modalità del trattamento;<br>
			della logica applicata in caso di trattamento effettuato con l'ausilio di strumenti elettronici;<br>
			degli estremi identificativi del titolare, dei responsabili e del rappresentante designato ai sensi dell'articolo 5, comma 2;<br>
			dei soggetti o delle categorie di soggetti ai quali i dati personali possono essere comunicati o che possono venirne a conoscenza in qualità di 
			rappresentante designato nel territorio dello Stato, di responsabili o incaricati.<br>
			L'interessato ha diritto di ottenere:<br>
			l'aggiornamento, la rettificazione ovvero, quando vi ha interesse, l'integrazione dei dati;<br>
			la cancellazione, la trasformazione in forma anonima o il blocco dei dati trattati in violazione di legge, 
			compresi quelli di cui non è necessaria la conservazione in relazione agli scopi per i quali i dati sono stati raccolti o successivamente trattati;<br>
			l'attestazione che le operazioni di cui alle lettere a) e b) sono state portate a conoscenza, anche per quanto riguarda il loro contenuto, 
			di coloro ai quali i dati sono stati comunicati o diffusi, eccettuato il caso in cui tale adempimento si rivela impossibile o comporta un impiego di mezzi 
			manifestamente sproporzionato rispetto al diritto tutelato.<br>
			L'interessato ha diritto di opporsi, in tutto o in parte:<br>
			per motivi legittimi al trattamento dei dati personali che lo riguardano, ancorché pertinenti allo scopo della raccolta;<br>
			al trattamento di dati personali che lo riguardano a fini di invio di materiale pubblicitario o di vendita diretta o per il compimento di ricerche 
			di mercato o di comunicazione commerciale.<br>
			Le eventuali richieste per l'esercizio di tali diritti vanno rivolte al Titolare:<br>
			Filippo Matteo Riggio, che risede in Via Brancon 116 - 37053 Nogara (VR).
		</p>
	</div>
</section>